# Default values for omar-geoscript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: omar-geoscript

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  hostname: omar-dev.ossim.io

  omarDb:
    name: null
    host: null
    user: null
    password: null
    port: null

  ingress:
    class: nginx
    enabled: true
    annotations: {}

  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true

  autoscaling:
    enabled: true

  useSpringConfigServer: false

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1500m
    memory: 2000Mi
  requests:
    cpu: 500m
    memory: 500Mi

autoscaling:
  enabled:
  targetCpu: 75

image:
  name: omar-geoscript
  tag: 2.15.9
  pullPolicy: Always

ingress:
  enabled:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  class: # defaults to nginx if not set

path: /omar-geoscript
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 380

readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 2
  timeoutSeconds: 3
  path: /omar-geoscript/actuator/health

terminationGracePeriodSeconds: 30

envVars:
  SPRING_CLOUD_CONFIG_LABEL: master
  KEY_STORE: /home/omar/es/admin.jks
  KEY_STORE_PASSWORD: kspass
  TRUST_STORE: /home/omar/es/truststore
  REMOTE_DEBUG:

configmaps: {}

extraInitContainers: []

sideCars: []

# Added for download support
downloadURL: https://omar-3pa-sar-download.ossim.io  
downloadRootDir: /3pa-comsar/ 
