apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "omar-geoscript.fullname" . }}"
  labels:
    {{- include "omar-geoscript.labels" . | nindent 4 }}
data:
  application.yaml: |-
    about:
      contactEmail: Kevin.Naquin@maxar.com
      releaseName: HystericalHyena
      releaseNumber: 1.0.0

    geoscript:
      evwhs:
        url: 'https://evwhs.digitalglobe.com/mapservice/wmsaccess?connectid=a59618a4-3656-4b09-ba85-934f162bd9d6&version=1.3.0&request=GetCapabilities'
        username: ''
        password: ''
      elasticsearch:
        url: "https://logging-es.logging.svc.cluster.local:9200/project.omar-dev*/_search?pretty"
      downloadURL: {{ .Values.downloadURL }}
      downloadRootDir: {{ .Values.downloadRootDir }}
      downloadMissions:
      {{- range .Values.downloadMissions }}
        - {{ . | quote }}
      {{- end }}
      downloadURL3D: {{ .Values.downloadURL3D }}
      downloadRootDir3D: {{ .Values.downloadRootDir3D }}
      downloadMissions3D:
      {{- range .Values.downloadMissions3D }}
        - {{ . | quote }}
      {{- end }}
    wfs:
      featureTypeNamespaces:
          - prefix: omar
            uri: http://omar.ossim.org

      datastores:
          - namespaceId: omar
            datastoreId: omar_prod
            datastoreParams:
              dbtype: postgis
              host: {{ .Values.global.omarDb.host }}
              port: "{{ .Values.global.omarDb.port }}"
              database: {{ .Values.global.omarDb.name }}
              user: {{ .Values.global.omarDb.user }}
              passwd: {{ .Values.global.omarDb.password }}
              'Expose primary keys': 'true'
              namespace: http://omar.ossim.org

      featureTypes:
          - name: raster_entry
            title: raster_entry
            description: ''
            keywords:
              - omar
              - raster_entry
              - features
            datastoreId: omar_prod

          - name: video_data_set
            title: video_data_set
            description: ''
            keywords:
              - omar
              - video_data_set
              - features
            datastoreId: omar_prod

    environments:
      production:
        dataSource:
          pooled: true
          jmxExport: true
          driverClassName: ${omarDb.driver}
          dialect:   ${omarDb.dialect}
          url:      ${omarDb.url}
          username: ${omarDb.username}
          password: ${omarDb.password}

    omarDb:
      host: {{ .Values.global.omarDb.host }}
      username: {{ .Values.global.omarDb.user }}
      password: {{ .Values.global.omarDb.password }}
      name: {{ .Values.global.omarDb.name }}
      port: {{ .Values.global.omarDb.port }}
      driver: org.postgresql.Driver
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${omarDb.host}:${omarDb.port}/${omarDb.name}

    serverDomain: ossim.io
    serverName: {{ .Values.global.hostname }}
    serverNamePki: pki-omar.${serverDomain}

    serverProtocol: https
